version: '3'
services:
  nginx-site:
    build: ./website/
    ports:
      - '80:80'
    networks:
      - counter
  server:
    build: ./goServeMe/
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
    networks:
      - counter
      - counterDB
    ports:
      - '3000:3000'
  redis:
    image: redis
    networks:
      - counterDB

networks:
  counter:
  counterDB: